# Generated by Django 5.1.2 on 2024-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_turma"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professores",
            fields=[
                ("professores_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=255)),
                ("nome", models.CharField(max_length=45)),
            ],
        ),
    ]
