# Generated by Django 5.1.2 on 2024-11-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_professores"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Professores",
            new_name="Professor",
        ),
        migrations.RenameField(
            model_name="professor",
            old_name="professores_id",
            new_name="professor_id",
        ),
    ]
