# Generated by Django 5.1.2 on 2024-11-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_professores_professor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("disciplina_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.professor",
                    ),
                ),
            ],
        ),
    ]
