# Generated by Django 5.1.2 on 2024-11-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_disciplina"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                ("trimestre_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=20)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
        ),
    ]
