# Generated by Django 5.1.2 on 2024-11-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_preconselho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("pkAluno", models.CharField(max_length=45, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255)),
                ("nomeAluno", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField()),
                ("turma", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.turma")),
            ],
        ),
    ]
