# Generated by Django 5.1.2 on 2024-11-29 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_aluno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("categoria_ocorrencia", models.CharField(max_length=100)),
                ("data_criacao", models.DateField()),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.aluno")),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
