# Generated by Django 5.1.2 on 2024-11-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ocorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConselhoClasse",
            fields=[
                ("conselho_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_conselho", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Em andamento", "Em andamento"),
                            ("Finalizado", "Finalizado"),
                        ],
                        default="Pendente",
                        max_length=15,
                    ),
                ),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.aluno")),
                ("trimestre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.trimestre")),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("nota_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "trimestre",
                    models.CharField(choices=[("1", "Primeiro"), ("2", "Segundo"), ("3", "Terceiro")], max_length=20),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.aluno")),
                ("conselho", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.conselhoclasse")),
                ("disciplina", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.disciplina")),
            ],
        ),
    ]
