# Generated by Django 5.1.2 on 2024-11-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_conselhoclasse_nota"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurmaHasDisciplina",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("disciplina", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.disciplina")),
                ("turma", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.turma")),
            ],
        ),
    ]
